### ISSUE TITLE
Panic during DB writeout (invalid IPv4 / IPv6 key)

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#96]
When building `goProbe` from branch `43-global-query` (commit `6821b8b414f4afea98a6bd84ef1eb0576249724a`) it crashed during (first) writeout:
```
panic: key is neither ipv4 nor ipv6

goroutine 38 [running]:
github.com/els0r/goProbe/pkg/types.Key.IsIPv4(...)
        /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/types/keyval.go:106
github.com/els0r/goProbe/pkg/types.Key.GetSip(...)
        /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/types/keyval.go:164
github.com/els0r/goProbe/pkg/types/hashmap.List.Sort.func1(0xc0001c2000?, 0xc000212f00?)
        /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/types/hashmap/list.go:43 +0x42b
sort.order2_func(...)
        /usr/local/go/src/sort/zsortfunc.go:299
sort.median_func({0xc0001432e8?, 0xc000212f00?}, 0x9e, 0x9f, 0xa0, 0xc000143188)
        /usr/local/go/src/sort/zsortfunc.go:308 +0x4a
sort.medianAdjacent_func(...)
        /usr/local/go/src/sort/zsortfunc.go:316
sort.choosePivot_func({0xc0001432e8?, 0xc000212f00?}, 0x0, 0x3c?)
        /usr/local/go/src/sort/zsortfunc.go:281 +0x110
sort.pdqsort_func({0xc0001432e8?, 0xc000212f00?}, 0x7f12e76065b8?, 0x18?, 0xc0001c2000?)
        /usr/local/go/src/sort/zsortfunc.go:89 +0xdb
sort.Slice({0x7eb240?, 0xc00021e330?}, 0xd5?)
        /usr/local/go/src/sort/slice.go:26 +0xfa
github.com/els0r/goProbe/pkg/types/hashmap.List.Sort({0xc0000bc000, 0xd5, 0xd5})
        /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/types/hashmap/list.go:39 +0x76
github.com/els0r/goProbe/pkg/goDB.dbData({0xc0001a61e0?, 0xb82a48?}, 0xc0001437a0?, 0x44dc35?)
        /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/goDB/db_writer.go:104 +0xd3
github.com/els0r/goProbe/pkg/goDB.(*DBWriter).Write(0xc000212ae0, 0xc000143d60?, {0xc00011f2f0?}, 0x4?)
        /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/goDB/db_writer.go:53 +0x23d
github.com/els0r/goProbe/pkg/goprobe/writeout.(*Handler).HandleWriteouts.func1()
        /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/goprobe/writeout/handler.go:217 +0x74d
created by github.com/els0r/goProbe/pkg/goprobe/writeout.(*Handler).HandleWriteouts
        /home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/goprobe/writeout/handler.go:179 +0xaa
```

It's unclear where that comes from (and there's been a lot of changes to slimcap that are not yet merged / matched in `goProbe`), but still this should be investigated.

In addition, upon restarting `goProbe` without removing the DB directory there was an error upon next (and all consecutive) writeouts:
```
2023-04-05T11:30:00.091+0200    error   writeout/handler.go:222 Error during writeout: seek /tmp/goprobe_test/eth0/2023/04/1680652800/proto.gpf: invalid argument       {"app_name": "goProbe_alpine", "app_version": "872abf81"}
```

This indicates that the failure protection implemented in #60 doesn't work as intended (maybe because it failed on the first attempt, leaving an empty file that now can't be `seek`ed:
```
fw-2:~# ll /tmp/goprobe_test/eth0/2023/04/1680652800/proto.gpf
-rw-r--r--    1 root     root             0 Apr  5 11:30 /tmp/goprobe_test/eth0/2023/04/1680652800/proto.gpf
```

DoD

- [x] Reproduce write failure on first attempt (and add case to tests) and handle accordingly
- [x] Track potential issue with invalid keys (as the panic indicates, this should not happen (tm))
- [x] Fix discovered hashmap iterator issue

**Comment by fako1024** [comment]
First analysis shows that it wants to seek to, well, somewhere that doesn't exist for sure:
```
2023-04-05T12:10:48.575+0200    error   writeout/handler.go:222 Error during writeout: seek to 72057594037927936 failed: seek /tmp/goprobe_test/eth0/2023/04/1680652800/proto.gpf: invalid argument    {"app_name": "goProbe_alpine_debug", "app_version": "872abf81"}
```
In addition, the file size of the `dip` column is huge, and a metadata analysis shows utter garbage:
```
└─ $ ▶ ./analyze-meta -path /tmp/goprobe_test/eth0/2023/04/1680652800/.blockmeta 

              Column: sip
    Number of Blocks: 0
     Number of Flows: 0 / 0 (IP v4 / v6)
             Traffic: bytes: received=0 sent=0; packets: received=0 sent=0
                Size: 4 bytes

        #    ts    time UTC    offset    len    raw len    encoder    ratio    #F v4    #F v6    drops    first 4 bytes        integrity check
                                                                                                                                                  
              Column: dip
    Number of Blocks: 0
     Number of Flows: 0 / 0 (IP v4 / v6)
             Traffic: bytes: received=0 sent=0; packets: received=0 sent=0
                Size: 17179869188 bytes

        #    ts    time UTC    offset    len    raw len    encoder    ratio    #F v4    #F v6    drops    first 4 bytes        integrity check
                                                                                                                                                  
              Column: proto
    Number of Blocks: 0
     Number of Flows: 0 / 0 (IP v4 / v6)
             Traffic: bytes: received=0 sent=0; packets: received=0 sent=0
                Size: 72057594037927936 bytes

        #    ts    time UTC    offset    len    raw len    encoder    ratio    #F v4    #F v6    drops    first 4 bytes        integrity check
                                                                                                                                                  
              Column: dport
    Number of Blocks: 0
     Number of Flows: 0 / 0 (IP v4 / v6)
             Traffic: bytes: received=0 sent=0; packets: received=0 sent=0
                Size: 288230376218820608 bytes

        #    ts    time UTC    offset    len    raw len    encoder    ratio    #F v4    #F v6    drops    first 4 bytes        integrity check
                                                                                                                                                  
              Column: bytes_rcvd
    Number of Blocks: 0
     Number of Flows: 0 / 0 (IP v4 / v6)
             Traffic: bytes: received=0 sent=0; packets: received=0 sent=0
                Size: 288511851128422400 bytes

        #    ts    time UTC    offset    len    raw len    encoder    ratio    #F v4    #F v6    drops    first 4 bytes        integrity check
                                                                                                                                                  
              Column: bytes_sent
    Number of Blocks: 0
     Number of Flows: 0 / 0 (IP v4 / v6)
             Traffic: bytes: received=0 sent=0; packets: received=0 sent=0
                Size: 281474976776192 bytes

        #    ts    time UTC    offset    len    raw len    encoder    ratio    #F v4    #F v6    drops    first 4 bytes        integrity check
                                                                                                                                                  
              Column: pkts_rcvd
    Number of Blocks: 0
     Number of Flows: 0 / 0 (IP v4 / v6)
             Traffic: bytes: received=0 sent=0; packets: received=0 sent=0
                Size: 282574488338432 bytes

        #    ts    time UTC    offset    len    raw len    encoder    ratio    #F v4    #F v6    drops    first 4 bytes        integrity check
                                                                                                            
              Column: pkts_sent
    Number of Blocks: 0
     Number of Flows: 0 / 0 (IP v4 / v6)
             Traffic: bytes: received=0 sent=0; packets: received=0 sent=0
                Size: 2199023256064 bytes

        #    ts    time UTC    offset    len    raw len    encoder    ratio    #F v4    #F v6    drops    first 4 bytes        integrity check
```
Almost seems as if the sizes are more or less random, as if uninitialized. If I wanted that I could have used C... :roll_eyes:

**Comment by fako1024** [comment]
Urgs, ok, that one's on me. From [here](https://go.dev/blog/defer-panic-and-recover):

> Panic is a built-in function that stops the ordinary flow of control and begins panicking. When the function F calls panic, execution of F stops, any deferred functions in F are executed normally, and then F returns to its caller.

In `db_writer.go` we call `defer dir.Close()`. After the whole thing panicked it went up the stack and _executed_ that, which of course defies the whole idea of only writing out _valid_ data. :see_no_evil:

**Comment by fako1024** [comment]
Added a test that reproduces a panic during write and was able to reproduce the show behavior (and of course fix it). Will now look into the root cause of the panic...

**Comment by fako1024** [comment]
I'm able to semi-reliably reproduce the issue on one of my sensors, and it seems that the issue is an empty key:
```
panic: key `[]` is neither ipv4 nor ipv6
```
I'll add some more debugging statements to figure out where that comes from.

**Comment by fako1024** [comment]
Turns out the issue is more fundamental and lodged deep in the iterator logic of the hashmap. There seems to be an inconsistency when iterating through the map item by item, as in: The length reported for the map (which is the actual number of items in the map and _correct_), the number of items iterated through is not the same (always smaller):
```
Got v4 length mismatch: len=216, count=118, lenNow=216
```
As can be seen from the value of `lenNow` (the length after completing all iterations) this is not a race condition. Most likely it's related to the map growing its hash table. Will investigate.

**Comment by fako1024** [comment]
No further crashes / issues on two independent test hosts encountered overnight, LGTM.
